name: main 

on: 
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - run: npm ci      

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pofider/johealthcheck:${{ github.event.release.tag_name }}
    
      - shell: bash   
        env:     
          KUBERNETES: ${{ secrets.KUBERNETES }} 
          TAG: ${{ github.event.release.tag_name }}       
        run: |    
          git clone https://github.com/pofider/kubernetes.git
          cd kubernetes 
          git checkout -b johealthcheck-${TAG}       
          git config --global user.name "pofider"
          git config --global user.email "honza.pofider@seznam.cz"

          sed -i 's/'"pofider\/johealthcheck"'\:\(.*\)/'"pofider\/johealthcheck"'\:'"${TAG}"'/' ./config/staging/johealthcheck.yaml
          sed -i 's/'"pofider\/johealthcheck"'\:\(.*\)/'"pofider\/johealthcheck"'\:'"${TAG}"'/' ./config/prod/johealthcheck.yaml
          git add config/staging/johealthcheck.yaml
          git add config/prod/johealthcheck.yaml
          git commit -m "Update the johealthcheck application"

          remote_repo="https://pofider:${KUBERNETES}@github.com/pofider/kubernetes.git"
          git push "${remote_repo}" HEAD:johealthcheck-${TAG}      